/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.kogics.kojo.story;

import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.DefaultEditorKit;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//net.kogics.kojo.story//StoryTeller//EN",
autostore = false)
public final class StoryTellerTopComponent extends TopComponent {

    private static StoryTellerTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "images/storyteller.png";
    private static final String PREFERRED_ID = "StoryTellerTopComponent";

    public StoryTellerTopComponent() {
        initComponents();

        StoryTeller st = (StoryTeller) StoryTeller.instance();
        st.setPreferredSize(this.getPreferredSize());
        add(st);

        final Action copyAction = new DefaultEditorKit.CopyAction();
        copyAction.setEnabled(false);
        ActionMap actionMap = getActionMap();
        actionMap.put(DefaultEditorKit.copyAction, copyAction);

        st.ep().addCaretListener(new CaretListener() {

            public void caretUpdate(CaretEvent e) {
                int dot = e.getDot();
                int mark = e.getMark();
                if (dot == mark) {
                    // no selection
                    copyAction.setEnabled(false);
                } else {
                    copyAction.setEnabled(true);
                }
            }
        });



        setName(NbBundle.getMessage(StoryTellerTopComponent.class, "CTL_StoryTellerTopComponent"));
        setToolTipText(NbBundle.getMessage(StoryTellerTopComponent.class, "HINT_StoryTellerTopComponent"));
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
//        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized StoryTellerTopComponent getDefault() {
        if (instance == null) {
            instance = new StoryTellerTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the StoryTellerTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized StoryTellerTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(StoryTellerTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof StoryTellerTopComponent) {
            return (StoryTellerTopComponent) win;
        }
        Logger.getLogger(StoryTellerTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        StoryTeller st = (StoryTeller) StoryTeller.instance();
        st.done();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
